# Generated by Django 6.0.4 on 2026-04-23 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='linked_debt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_payments', to='finances.debt'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='linked_savings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_contributions', to='finances.savingsgoal'),
        ),
    ]
