# Generated by Django 6.0.4 on 2026-04-23 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_transaction_linked_debt_transaction_linked_savings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionlineitem',
            name='linked_debt',
        ),
        migrations.RemoveField(
            model_name='transactionlineitem',
            name='linked_savings',
        ),
        migrations.AddField(
            model_name='transaction',
            name='linked_budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_transactions', to='finances.budget'),
        ),
    ]
