# Generated by Django 6.0.4 on 2026-04-28 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_remove_transactionlineitem_linked_debt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionlineitem',
            name='category',
        ),
        migrations.AddField(
            model_name='transactionlineitem',
            name='linked_budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='split_transactions', to='finances.budget'),
        ),
    ]
